spring:
  flyway:
    locations: classpath:db/migration-postgres

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crm_platform}
    username: ${DB_USER:crm_user}
    password: ${DB_PASSWORD:crm_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect