/**
 * Error Code Enum
 * Mirrors backend ErrorCode.java enum
 * 
 * This provides type-safe error code constants that match the backend.
 * Keep this synchronized with backend/shared-lib ErrorCode.java
 */
export enum ErrorCode {
  // AUTH (001-099)
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_TOKEN_EXPIRED = 'AUTH_002',
  AUTH_TOKEN_INVALID = 'AUTH_003',
  AUTH_TOKEN_REVOKED = 'AUTH_004',
  AUTH_TOKEN_MISSING = 'AUTH_005',
  AUTH_TOKEN_MALFORMED = 'AUTH_006',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_007',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_008',
  AUTH_ACCOUNT_LOCKED = 'AUTH_009',
  AUTH_ACCOUNT_INACTIVE = 'AUTH_010',
  AUTH_ACCOUNT_SUSPENDED = 'AUTH_011',
  AUTH_ACCOUNT_DELETED = 'AUTH_012',
  AUTH_PASSWORD_EXPIRED = 'AUTH_013',
  AUTH_PASSWORD_RESET_REQUIRED = 'AUTH_014',
  AUTH_MFA_REQUIRED = 'AUTH_020',
  AUTH_MFA_INVALID = 'AUTH_021',
  AUTH_MFA_EXPIRED = 'AUTH_022',
  AUTH_INSUFFICIENT_PERMISSION = 'AUTH_023',
  AUTH_ACCESS_DENIED = 'AUTH_024',
  AUTH_VALIDATION_FAILED = 'AUTH_033',

  // USER (100-199)
  USER_NOT_FOUND = 'USER_100',
  USER_ALREADY_EXISTS = 'USER_101',
  USER_EMAIL_ALREADY_EXISTS = 'USER_102',
  USER_USERNAME_ALREADY_EXISTS = 'USER_103',
  USER_PHONE_ALREADY_EXISTS = 'USER_104',
  USER_INACTIVE = 'USER_105',
  USER_SUSPENDED = 'USER_106',
  USER_DELETED = 'USER_107',
  USER_EMAIL_VERIFICATION_REQUIRED = 'USER_113',

  // ORDER (200-299)
  ORDER_NOT_FOUND = 'ORDER_200',
  ORDER_ALREADY_EXISTS = 'ORDER_201',
  ORDER_INSUFFICIENT_BALANCE = 'ORDER_202',
  ORDER_INSUFFICIENT_STOCK = 'ORDER_203',
  ORDER_CANNOT_CANCEL = 'ORDER_205',
  ORDER_ALREADY_CANCELLED = 'ORDER_207',
  ORDER_EXPIRED = 'ORDER_210',

  // PAYMENT (300-399)
  PAYMENT_NOT_FOUND = 'PAYMENT_300',
  PAYMENT_FAILED = 'PAYMENT_301',
  PAYMENT_DECLINED = 'PAYMENT_302',
  PAYMENT_INSUFFICIENT_FUNDS = 'PAYMENT_305',
  PAYMENT_CARD_DECLINED = 'PAYMENT_310',
  PAYMENT_CARD_EXPIRED = 'PAYMENT_311',
  PAYMENT_GATEWAY_ERROR = 'PAYMENT_318',

  // VALIDATION (400-499)
  VALIDATION_FAILED = 'VALIDATION_400',
  VALIDATION_EMAIL_REQUIRED = 'VALIDATION_401',
  VALIDATION_EMAIL_FORMAT = 'VALIDATION_402',
  VALIDATION_PASSWORD_REQUIRED = 'VALIDATION_403',
  VALIDATION_PASSWORD_MIN_LENGTH = 'VALIDATION_404',
  VALIDATION_USERNAME_REQUIRED = 'VALIDATION_406',
  VALIDATION_USERNAME_SIZE = 'VALIDATION_407',

  // SYSTEM (500-599)
  SYSTEM_INTERNAL_ERROR = 'SYSTEM_500',
  SYSTEM_SERVICE_UNAVAILABLE = 'SYSTEM_501',
  SYSTEM_TIMEOUT = 'SYSTEM_504',
  SYSTEM_RATE_LIMIT_EXCEEDED = 'SYSTEM_505',

  // DATABASE (600-699)
  DATABASE_CONNECTION_ERROR = 'DATABASE_600',
  DATABASE_TIMEOUT = 'DATABASE_601',
  DATABASE_DEADLOCK = 'DATABASE_605',

  // EXTERNAL_API (700-799)
  EXTERNAL_API_TIMEOUT = 'EXTERNAL_700',
  EXTERNAL_API_UNAVAILABLE = 'EXTERNAL_701',
  EXTERNAL_API_ERROR = 'EXTERNAL_702',

  // CRM (800-899)
  CRM_CUSTOMER_NOT_FOUND = 'CRM_800',
  CRM_CUSTOMER_ALREADY_EXISTS = 'CRM_801',
  CRM_LEAD_NOT_FOUND = 'CRM_802',
  CRM_OPPORTUNITY_NOT_FOUND = 'CRM_804',
  CRM_TASK_NOT_FOUND = 'CRM_807',
}

/**
 * Type guard to check if a string is a valid ErrorCode
 */
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ErrorCode).includes(code as ErrorCode);
}

/**
 * Get error code category from the code string
 */
export function getErrorCategory(code: string): string {
  return code.split('_')[0] || 'UNKNOWN';
}
